[package]
name = "env"
description = "Module for reading .env files"
repository = "https://github.com/KiwuOrg/lpm-env"
owners = ["sekta"]

[versions]

[versions."1.0.0"]
source = "https://github.com/KiwuOrg/lpm-env/archive/refs/tags/1.0.0.zip"
hash = "sha256-aebbd2a65305b7dcb2826e22d38603a9511655a314dfeb2eb84c095b9a3f5f9e"
dependencies = {}
